#%RAML 1.0
title: exchangeMulesoft
version: v1
baseUri: https://api.coppel.com/exchange-mulesoft
mediaType: application/json

/hello:
  get:
    description: Devuelve un saludo simple.
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              message: string
            example:
              message: "Hello World with Exchange v1.0.0"
