#%RAML 1.0
title: exchangeMulesoft
version: v1
baseUri: https://api.coppel.com/exchange-mulesoft
mediaType: application/json

types:
  Cuenta:
    type: object
    properties:
      id: integer
      numeroCuenta: string
      titular: string
      saldo: number

/cuentas:
  get:
    description: Listar todas las cuentas dummy
    responses:
      200:
        body:
          application/json:
            type: Cuenta[]
  post:
    description: Crear una nueva cuenta en memoria
    body:
      application/json:
        type: Cuenta
    responses:
      201:
        body:
          application/json:
            type: Cuenta
  put: 
    description: Actualizar una cuenta dummy en memoria
    body:
      application/json:
        type: Cuenta
    responses:
      200:
        body:
          application/json:
            type: Cuenta

/cuentas/{id}:
  get:
    description: Obtener una cuenta dummy por ID
    responses:
      200:
        body:
          application/json:
            type: Cuenta
  delete:
    description: Eliminar una cuenta dummy por ID
    responses:
      204:
        description: Cuenta eliminada
